// src/components/NetworkList.tsx
import React from 'react';
import { WiFiNetwork } from '../types/network';
import { Signal, Lock, LockKeyhole, ShieldAlert } from 'lucide-react';

interface NetworkListProps {
  networks: WiFiNetwork[];
}

export function NetworkList({ networks }: NetworkListProps) {
  const getSignalIcon = (strength: number) => {
    if (strength >= -50) return <Signal className="w-5 h-5 text-green-600" />;
    if (strength >= -70) return <Signal className="w-5 h-5 text-yellow-600" />;
    return <Signal className="w-5 h-5 text-red-600" />;
  };

  const getSecurityIcon = (security: WiFiNetwork['security']) => {
    switch (security) {
      case 'WPA3':
        return <LockKeyhole className="w-5 h-5 text-green-600" />;
      case 'WPA2':
        return <Lock className="w-5 h-5 text-blue-600" />;
      default:
        return <ShieldAlert className="w-5 h-5 text-red-600" />;
    }
  };

  return (
    <div className="space-y-4">
      {networks.map((network) => (
        <div
          key={network.id}
          className="bg-white rounded-lg shadow-md p-4 hover:shadow-lg transition-shadow"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              {getSignalIcon(network.signalStrength)}
              <div>
                <h3 className="font-semibold text-gray-900">{network.ssid}</h3>
                <p className="text-sm text-gray-600">
                  {network.frequency}GHz - Ch {network.channel}
                </p>
              </div>
            </div>
            <div className="flex items-center space-x-4">
              {getSecurityIcon(network.security)}
              <span className="text-sm font-mono text-gray-700">
                {network.signalStrength} dBm
              </span>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

// app/components/NetworkList.svelte
<script lang="ts">
  import { type WiFiNetwork } from '../services/wifi.service';
  
  export let networks: WiFiNetwork[] = [];

  function getSignalIcon(strength: number): string {
    if (strength >= -50) return '📶';
    if (strength >= -60) return '📶';
    if (strength >= -70) return '📶';
    return '📶';
  }

  function getSecurityIcon(type: string): string {
    return type.includes('WPA3') ? '🔒' : 
           type.includes('WPA2') ? '🔐' : 
           type.includes('WPA') ? '🔓' : '⚠️';
  }
</script>

<scrollView>
  <stackLayout>
    {#each networks as network}
      <gridLayout columns="auto, *, auto, auto" class="network-item">
        <label col="0" text={getSignalIcon(network.signalStrength)} class="icon" />
        <stackLayout col="1">
          <label text={network.ssid} class="ssid" />
          <label text={`${network.frequency}GHz - Ch ${network.channel}`} class="details" />
        </stackLayout>
        <label col="2" text={getSecurityIcon(network.security)} class="icon" />
        <label col="3" text={`${network.signalStrength} dBm`} class="signal" />
      </gridLayout>
    {/each}
  </stackLayout>
</scrollView>

<style>
  .network-item {
    padding: 12;
    margin: 4 8;
    background-color: white;
    border-radius: 8;
  }

  .ssid {
    font-size: 16;
    font-weight: bold;
  }

  .details {
    font-size: 14;
    color: #666;
  }

  .icon {
    font-size: 20;
    margin: 0 8;
  }

  .signal {
    font-size: 14;
    color: #444;
  }
</style>
